/**
 * Expo Config Plugin — Incoming Call & Notification Support.
 *
 * Since android/ is gitignored and regenerated by EAS Build,
 * this plugin injects required AndroidManifest changes:
 *  - showWhenLocked / turnScreenOn on MainActivity (lockscreen calls)
 *  - FOREGROUND_SERVICE_DATA_SYNC permission (Notifee background work)
 *  - RECEIVE_BOOT_COMPLETED permission (re-register token after reboot)
 */
const { withAndroidManifest, AndroidConfig } = require("expo/config-plugins");

function withCallNotifications(config) {
  // ─── Add permissions ──────────────────────────────────────────────────────
  config = AndroidConfig.Permissions.withPermissions(config, [
    "android.permission.FOREGROUND_SERVICE_DATA_SYNC",
    "android.permission.RECEIVE_BOOT_COMPLETED",
  ]);

  // ─── Modify MainActivity attributes ───────────────────────────────────────
  config = withAndroidManifest(config, (config) => {
    const manifest = config.modResults;
    const application = manifest.manifest.application?.[0];
    if (!application) return config;

    const activities = application.activity || [];
    const mainActivity = activities.find(
      (a) => a.$?.["android:name"] === ".MainActivity",
    );

    if (mainActivity) {
      // ★ Show call UI over lockscreen
      mainActivity.$["android:showWhenLocked"] = "true";
      mainActivity.$["android:turnScreenOn"] = "true";
    }

    return config;
  });

  return config;
}

module.exports = withCallNotifications;
