/**
 * Expo Config Plugin — Incoming Call, Notification, and Background FCM Support.
 *
 * Since android/ is gitignored and regenerated by EAS Build,
 * this plugin injects required configuration:
 *  - showWhenLocked / turnScreenOn on MainActivity (lockscreen calls)
 *  - FOREGROUND_SERVICE_DATA_SYNC permission (Notifee background work)
 *  - RECEIVE_BOOT_COMPLETED permission (re-register token after reboot)
 *  - Notifee Maven repository (required for Notifee Android dependency)
 */
const {
  withAndroidManifest,
  withProjectBuildGradle,
  AndroidConfig,
} = require("expo/config-plugins");

function withCallNotifications(config) {
  // ─── Add permissions ──────────────────────────────────────────────────────
  config = AndroidConfig.Permissions.withPermissions(config, [
    "android.permission.FOREGROUND_SERVICE_DATA_SYNC",
    "android.permission.RECEIVE_BOOT_COMPLETED",
  ]);

  // ─── Modify MainActivity attributes ───────────────────────────────────────
  config = withAndroidManifest(config, (config) => {
    const manifest = config.modResults;
    const application = manifest.manifest.application?.[0];
    if (!application) return config;

    const activities = application.activity || [];
    const mainActivity = activities.find(
      (a) => a.$?.["android:name"] === ".MainActivity",
    );

    if (mainActivity) {
      // ★ Show call UI over lockscreen
      mainActivity.$["android:showWhenLocked"] = "true";
      mainActivity.$["android:turnScreenOn"] = "true";
    }

    return config;
  });

  // ─── Add Notifee Maven repo to project-level build.gradle ─────────────────
  // ★ CRITICAL: Notifee ships its Android library as a local AAR.
  // Without this Maven declaration, Gradle can't resolve @notifee/react-native.
  config = withProjectBuildGradle(config, (config) => {
    if (config.modResults.language === "groovy") {
      const contents = config.modResults.contents;
      const notifeeRepo = `maven { url "$rootDir/../node_modules/@notifee/react-native/android/libs" }`;

      if (!contents.includes("@notifee/react-native")) {
        // Insert after jitpack or after mavenCentral in allprojects
        config.modResults.contents = contents.replace(
          /maven\s*\{\s*url\s*'https:\/\/www\.jitpack\.io'\s*\}/,
          `maven { url 'https://www.jitpack.io' }\n        ${notifeeRepo}`,
        );
      }
    }
    return config;
  });

  return config;
}

module.exports = withCallNotifications;
